[package]
name = "hub-demo-cli"
version = "0.1.0"
edition = "2021"

[workspace]

[dependencies]
hub_protocol = { path = "../crates/hub_protocol" }
tokio = { version = "1.0", features = ["full"] }
anyhow = "1.0"
chrono = "0.4"